In [1]:
#import torch
import pufferlib.vector
import pufferlib.ocean

RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000

RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000

In [2]:
env_creator = pufferlib.ocean.env_creator("puffer_g2048")

In [3]:
env = env_creator()

In [4]:
env.reset(seed=300)

(array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8), [])

In [5]:
import numpy as np

In [12]:
env.step(actions= [3.])

(array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8),
 array([-0.5], dtype=float32),
 array([False]),
 array([False]),
 [])

In [7]:
vecenv = pufferlib.vector.make(env_creator, num_envs=2, num_workers=2, batch_size=1,
        backend=pufferlib.vector.Multiprocessing, env_kwargs={'num_envs': 4096})

In [8]:
vecenv.reset()[0].shape

(4096, 16)